"""Cover letter generation (currently a placeholder stub — see issue #229).

This module owns the cover-letter side of the build_resume pipeline. The
real generator (LLM-driven content, DOCX/PDF rendering) is tracked in
issue #229; until then, generate_cover_letter() writes a clearly-labeled
markdown placeholder so that --cover-letter wires through the CLI end
to end and consumers can adopt the one-liner workflow today.
"""

from __future__ import annotations

import argparse
from pathlib import Path

if __package__ in {None, ""}:
    import document_export
else:
    from scripts import document_export


COVER_LETTER_PLACEHOLDER_TEMPLATE = """# Cover Letter (placeholder)

> This is a stub generated by `scripts/cover_letter.py`. Real cover-letter
> content (LLM-tailored body, DOCX/PDF rendering) is tracked in
> [issue #229](https://github.com/jsmithpkp21/resume-builder/issues/229).

- Company: {company}
- Role: {role}
- Generated for output dir: `{output_dir}`

TODO: replace this placeholder with a tailored cover letter when #229 ships.
"""


def generate_cover_letter(
    *,
    args: argparse.Namespace,
    output_dir: Path,
    company: str,
    role: str,
) -> list[Path]:
    """Write a placeholder cover-letter markdown file and return its path.

    `output_dir` is the cover-letter output directory (already
    `<application-root>/cover_letters/`); the caller is responsible for
    selecting it. The placeholder body references issue #229 so reviewers
    immediately see this is not the final artifact.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    slug = document_export.snake_case(company) if company else "company"
    target = output_dir / f"{slug}_cover_letter.md"
    body = COVER_LETTER_PLACEHOLDER_TEMPLATE.format(
        company=company or "(unknown)",
        role=role or "(unknown)",
        output_dir=output_dir,
    )
    target.write_text(body, encoding="utf-8")
    return [target]
