#!/usr/bin/env bash
set -euo pipefail

# install_playwright_runtime.sh — install the Playwright layer + Chromium
# browser binaries into the resume-builder Python venv.
#
# Why this exists: scripts/jd_ingest.py has an opt-in Playwright fetch path
# gated on the RESUME_BUILDER_ENABLE_PLAYWRIGHT env var and a successful
# `import playwright`. The fetcher silently no-ops when the package is not
# installed, so this script only needs to run on machines that will
# actually exercise the JS-rendered JD path (Workday, Western Union
# careers, etc.). Idempotent — safe to re-run after a WSL wipe.
#
# Layer source: layers/playwright/requirements.txt is generated by
# scripts/prepare_playwright_layer.py (synced from base_repo) and pins
# playwright==1.35.0 alongside the rest of the resume-builder runtime
# deps. Chromium is installed via Playwright's own `install --with-deps`
# which pulls the matching browser build for the pinned package version.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LAYER_REQ="${REPO_ROOT}/layers/playwright/requirements.txt"
VENV_PATH="${VENV_PATH:-${HOME}/envs/resume-builder-env}"

if [ ! -f "$LAYER_REQ" ]; then
    echo "❌ Layer requirements file not found: $LAYER_REQ" >&2
    echo "   Run: python scripts/prepare_playwright_layer.py" >&2
    exit 1
fi

if [ ! -d "$VENV_PATH" ]; then
    echo "❌ venv not found at: $VENV_PATH" >&2
    echo "   Set VENV_PATH or run: bash scripts/create_env.sh" >&2
    exit 1
fi

# shellcheck disable=SC1091
source "${VENV_PATH}/bin/activate"

echo "📦 Installing Playwright layer deps from ${LAYER_REQ}..."
pip install --no-cache-dir -r "$LAYER_REQ"

# `playwright install --with-deps chromium` pulls the matching Chromium
# build and the OS libraries it needs (libgbm, libasound, etc.). Single
# browser only — Firefox / Webkit aren't needed for JD ingest.
echo "🌐 Installing Chromium + OS deps via playwright..."
playwright install --with-deps chromium

echo "✅ Playwright runtime ready."
echo "   Activate: export RESUME_BUILDER_ENABLE_PLAYWRIGHT=1"
